server:
  port: 8082

spring:
  application:
    name: spring-boot-keycloak
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${CLIENT_ID:spring-boot-keycloak-client}
            client-secret: ${CLIENT_SECRET:rhQbdBa0PGmKt7DSV7BaagMIGOT292IF}
            scope: openid,profile,email
            redirect-uri: http://localhost:8082/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8088/realms/spring-boot-keycloak-realm

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG